### ISSUE TITLE
Error when python3 create_structured_csv.py

### ISSUE THREAD

**Issue by limengmingx** [varun196/knowledge_graph_from_unstructured_text#1]
I can run the first and second command successfully, but get error when i working 
 `python3 create_structured_csv.py`
The error is like below:
```
input_data
Traceback (most recent call last):
  File "create_structured_csv.py", line 58, in <module>
    main()
  File "create_structured_csv.py", line 30, in main
    df = pd.read_csv(curr_dir +"/data/output/kg/"+file_name+".txt-out.csv")
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 435, in _read
    data = parser.read(nrows)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1139, in read
    ret = self._engine.read(nrows)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1995, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 899, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 914, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 968, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 955, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2172, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 3 fields in line 30, saw 4
```

**Comment by varun196** [comment]
Input data contains $80,000; which when converted to and read back from CSV throws an error due to the ','. Current hot-fix is to remove ',' i.e. convert '$80,000' to '80000'. 

Created issue #2.
