### ISSUE TITLE
Relation-Extraction: "process_large_corpus.sh" file not found

### ISSUE THREAD

**Issue by Kojo7** [varun196/knowledge_graph_from_unstructured_text#7]
Hello guys,

Can someone please help me with this error. The 'process_large_corpus.sh' file is in the right directory so I do not understand what the issue is..??

`Traceback (most recent call last):
  File "relation_extractor.py", line 27, in <module>
    Stanford_Relation_Extractor()
  File "relation_extractor.py", line 17, in Stanford_Relation_Extractor
    p = subprocess.Popen(['./process_large_corpus.sh',f,f + '-out.csv'], stdout=subprocess.PIPE) 
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './process_large_corpus.sh': './process_large_corpus.sh'
`

Thanks very much..!!

**Comment by ZQY0607** [comment]
process_large_corpus.sh
Change 'Python' in line 30 of the code to 'Python 3'
